<?php
/**
 * Marketplace
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketplace API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.10.8
 * Contact: support@lyra-network.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * Marketplace Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Marketplace implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Marketplace';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'href' => 'string',
        'uuid' => 'string',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'reference' => 'string',
        'description' => 'string',
        'billing_method' => 'string',
        'bic' => 'string',
        'iban' => 'string',
        'vads_key' => 'string',
        'vads_cert' => 'string',
        'status' => 'string',
        'links' => '\Swagger\Client\Model\MarketplaceLinks',
        'max_capture_delay' => 'int',
        'tva_rate' => 'string',
        'currencies' => '\Swagger\Client\Model\MarketplaceCurrency[]',
        'vouchers' => '\Swagger\Client\Model\MarketplaceVoucher[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'href' => null,
        'uuid' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'reference' => null,
        'description' => null,
        'billing_method' => null,
        'bic' => null,
        'iban' => null,
        'vads_key' => null,
        'vads_cert' => null,
        'status' => null,
        'links' => null,
        'max_capture_delay' => null,
        'tva_rate' => 'decimal',
        'currencies' => null,
        'vouchers' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'href' => 'href',
        'uuid' => 'uuid',
        'created_at' => 'created_at',
        'updated_at' => 'updated_at',
        'reference' => 'reference',
        'description' => 'description',
        'billing_method' => 'billing_method',
        'bic' => 'bic',
        'iban' => 'iban',
        'vads_key' => 'vads_key',
        'vads_cert' => 'vads_cert',
        'status' => 'status',
        'links' => 'links',
        'max_capture_delay' => 'max_capture_delay',
        'tva_rate' => 'tva_rate',
        'currencies' => 'currencies',
        'vouchers' => 'vouchers'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'href' => 'setHref',
        'uuid' => 'setUuid',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'reference' => 'setReference',
        'description' => 'setDescription',
        'billing_method' => 'setBillingMethod',
        'bic' => 'setBic',
        'iban' => 'setIban',
        'vads_key' => 'setVadsKey',
        'vads_cert' => 'setVadsCert',
        'status' => 'setStatus',
        'links' => 'setLinks',
        'max_capture_delay' => 'setMaxCaptureDelay',
        'tva_rate' => 'setTvaRate',
        'currencies' => 'setCurrencies',
        'vouchers' => 'setVouchers'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'href' => 'getHref',
        'uuid' => 'getUuid',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'reference' => 'getReference',
        'description' => 'getDescription',
        'billing_method' => 'getBillingMethod',
        'bic' => 'getBic',
        'iban' => 'getIban',
        'vads_key' => 'getVadsKey',
        'vads_cert' => 'getVadsCert',
        'status' => 'getStatus',
        'links' => 'getLinks',
        'max_capture_delay' => 'getMaxCaptureDelay',
        'tva_rate' => 'getTvaRate',
        'currencies' => 'getCurrencies',
        'vouchers' => 'getVouchers'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const BILLING_METHOD_CASHOUT = 'CASHOUT';
    const BILLING_METHOD_MONTHLY = 'MONTHLY';
    const STATUS_ACTIVE = 'ACTIVE';
    const STATUS_INACTIVE = 'INACTIVE';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getBillingMethodAllowableValues()
    {
        return [
            self::BILLING_METHOD_CASHOUT,
            self::BILLING_METHOD_MONTHLY,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_ACTIVE,
            self::STATUS_INACTIVE,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['href'] = isset($data['href']) ? $data['href'] : null;
        $this->container['uuid'] = isset($data['uuid']) ? $data['uuid'] : null;
        $this->container['created_at'] = isset($data['created_at']) ? $data['created_at'] : null;
        $this->container['updated_at'] = isset($data['updated_at']) ? $data['updated_at'] : null;
        $this->container['reference'] = isset($data['reference']) ? $data['reference'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['billing_method'] = isset($data['billing_method']) ? $data['billing_method'] : null;
        $this->container['bic'] = isset($data['bic']) ? $data['bic'] : null;
        $this->container['iban'] = isset($data['iban']) ? $data['iban'] : null;
        $this->container['vads_key'] = isset($data['vads_key']) ? $data['vads_key'] : null;
        $this->container['vads_cert'] = isset($data['vads_cert']) ? $data['vads_cert'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['links'] = isset($data['links']) ? $data['links'] : null;
        $this->container['max_capture_delay'] = isset($data['max_capture_delay']) ? $data['max_capture_delay'] : null;
        $this->container['tva_rate'] = isset($data['tva_rate']) ? $data['tva_rate'] : null;
        $this->container['currencies'] = isset($data['currencies']) ? $data['currencies'] : null;
        $this->container['vouchers'] = isset($data['vouchers']) ? $data['vouchers'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['uuid']) && (mb_strlen($this->container['uuid']) < 1)) {
            $invalidProperties[] = "invalid value for 'uuid', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['reference'] === null) {
            $invalidProperties[] = "'reference' can't be null";
        }
        if ((mb_strlen($this->container['reference']) < 1)) {
            $invalidProperties[] = "invalid value for 'reference', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['description'] === null) {
            $invalidProperties[] = "'description' can't be null";
        }
        if ((mb_strlen($this->container['description']) < 1)) {
            $invalidProperties[] = "invalid value for 'description', the character length must be bigger than or equal to 1.";
        }

        $allowedValues = $this->getBillingMethodAllowableValues();
        if (!is_null($this->container['billing_method']) && !in_array($this->container['billing_method'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'billing_method', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['bic']) && (mb_strlen($this->container['bic']) > 11)) {
            $invalidProperties[] = "invalid value for 'bic', the character length must be smaller than or equal to 11.";
        }

        if (!is_null($this->container['iban']) && (mb_strlen($this->container['iban']) > 34)) {
            $invalidProperties[] = "invalid value for 'iban', the character length must be smaller than or equal to 34.";
        }

        if (!is_null($this->container['vads_key']) && (mb_strlen($this->container['vads_key']) < 1)) {
            $invalidProperties[] = "invalid value for 'vads_key', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['vads_cert']) && (mb_strlen($this->container['vads_cert']) < 1)) {
            $invalidProperties[] = "invalid value for 'vads_cert', the character length must be bigger than or equal to 1.";
        }

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['currencies'] === null) {
            $invalidProperties[] = "'currencies' can't be null";
        }
        if ($this->container['vouchers'] === null) {
            $invalidProperties[] = "'vouchers' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets href
     *
     * @return string
     */
    public function getHref()
    {
        return $this->container['href'];
    }

    /**
     * Sets href
     *
     * @param string $href href
     *
     * @return $this
     */
    public function setHref($href)
    {
        $this->container['href'] = $href;

        return $this;
    }

    /**
     * Gets uuid
     *
     * @return string
     */
    public function getUuid()
    {
        return $this->container['uuid'];
    }

    /**
     * Sets uuid
     *
     * @param string $uuid Unique identifier. This field is automatically generated.
     *
     * @return $this
     */
    public function setUuid($uuid)
    {

        if (!is_null($uuid) && (mb_strlen($uuid) < 1)) {
            throw new \InvalidArgumentException('invalid length for $uuid when calling Marketplace., must be bigger than or equal to 1.');
        }

        $this->container['uuid'] = $uuid;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at Creation date. This field is automatically generated.
     *
     * @return $this
     */
    public function setCreatedAt($created_at)
    {
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime $updated_at Date of the last modification. This field is automatically generated.
     *
     * @return $this
     */
    public function setUpdatedAt($updated_at)
    {
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets reference
     *
     * @return string
     */
    public function getReference()
    {
        return $this->container['reference'];
    }

    /**
     * Sets reference
     *
     * @param string $reference reference
     *
     * @return $this
     */
    public function setReference($reference)
    {

        if ((mb_strlen($reference) < 1)) {
            throw new \InvalidArgumentException('invalid length for $reference when calling Marketplace., must be bigger than or equal to 1.');
        }

        $this->container['reference'] = $reference;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return $this
     */
    public function setDescription($description)
    {

        if ((mb_strlen($description) < 1)) {
            throw new \InvalidArgumentException('invalid length for $description when calling Marketplace., must be bigger than or equal to 1.');
        }

        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets billing_method
     *
     * @return string
     */
    public function getBillingMethod()
    {
        return $this->container['billing_method'];
    }

    /**
     * Sets billing_method
     *
     * @param string $billing_method Defines whether commission is computed against each order or monthly.
     *
     * @return $this
     */
    public function setBillingMethod($billing_method)
    {
        $allowedValues = $this->getBillingMethodAllowableValues();
        if (!is_null($billing_method) && !in_array($billing_method, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'billing_method', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['billing_method'] = $billing_method;

        return $this;
    }

    /**
     * Gets bic
     *
     * @return string
     */
    public function getBic()
    {
        return $this->container['bic'];
    }

    /**
     * Sets bic
     *
     * @param string $bic Bank code of the marketplace.
     *
     * @return $this
     */
    public function setBic($bic)
    {
        if (!is_null($bic) && (mb_strlen($bic) > 11)) {
            throw new \InvalidArgumentException('invalid length for $bic when calling Marketplace., must be smaller than or equal to 11.');
        }

        $this->container['bic'] = $bic;

        return $this;
    }

    /**
     * Gets iban
     *
     * @return string
     */
    public function getIban()
    {
        return $this->container['iban'];
    }

    /**
     * Sets iban
     *
     * @param string $iban Account number of the marketplace.
     *
     * @return $this
     */
    public function setIban($iban)
    {
        if (!is_null($iban) && (mb_strlen($iban) > 34)) {
            throw new \InvalidArgumentException('invalid length for $iban when calling Marketplace., must be smaller than or equal to 34.');
        }

        $this->container['iban'] = $iban;

        return $this;
    }

    /**
     * Gets vads_key
     *
     * @return string
     */
    public function getVadsKey()
    {
        return $this->container['vads_key'];
    }

    /**
     * Sets vads_key
     *
     * @param string $vads_key Marketplace identifier with Lyra Collect. This field is generated by Lyra Collect.
     *
     * @return $this
     */
    public function setVadsKey($vads_key)
    {

        if (!is_null($vads_key) && (mb_strlen($vads_key) < 1)) {
            throw new \InvalidArgumentException('invalid length for $vads_key when calling Marketplace., must be bigger than or equal to 1.');
        }

        $this->container['vads_key'] = $vads_key;

        return $this;
    }

    /**
     * Gets vads_cert
     *
     * @return string
     */
    public function getVadsCert()
    {
        return $this->container['vads_cert'];
    }

    /**
     * Sets vads_cert
     *
     * @param string $vads_cert Marketplace certificate with Lyra Collect. This field is generated by Lyra Collect
     *
     * @return $this
     */
    public function setVadsCert($vads_cert)
    {

        if (!is_null($vads_cert) && (mb_strlen($vads_cert) < 1)) {
            throw new \InvalidArgumentException('invalid length for $vads_cert when calling Marketplace., must be bigger than or equal to 1.');
        }

        $this->container['vads_cert'] = $vads_cert;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status Current status of the marketplace. This field is managed by Lyra Collect.
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($status) && !in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets links
     *
     * @return \Swagger\Client\Model\MarketplaceLinks
     */
    public function getLinks()
    {
        return $this->container['links'];
    }

    /**
     * Sets links
     *
     * @param \Swagger\Client\Model\MarketplaceLinks $links links
     *
     * @return $this
     */
    public function setLinks($links)
    {
        $this->container['links'] = $links;

        return $this;
    }

    /**
     * Gets max_capture_delay
     *
     * @return int
     */
    public function getMaxCaptureDelay()
    {
        return $this->container['max_capture_delay'];
    }

    /**
     * Sets max_capture_delay
     *
     * @param int $max_capture_delay max_capture_delay
     *
     * @return $this
     */
    public function setMaxCaptureDelay($max_capture_delay)
    {
        $this->container['max_capture_delay'] = $max_capture_delay;

        return $this;
    }

    /**
     * Gets tva_rate
     *
     * @return string
     */
    public function getTvaRate()
    {
        return $this->container['tva_rate'];
    }

    /**
     * Sets tva_rate
     *
     * @param string $tva_rate VAT rate, expressed in %. For example: 20,4 means 20,4% of TVA rate.
     *
     * @return $this
     */
    public function setTvaRate($tva_rate)
    {
        $this->container['tva_rate'] = $tva_rate;

        return $this;
    }

    /**
     * Gets currencies
     *
     * @return \Swagger\Client\Model\MarketplaceCurrency[]
     */
    public function getCurrencies()
    {
        return $this->container['currencies'];
    }

    /**
     * Sets currencies
     *
     * @param \Swagger\Client\Model\MarketplaceCurrency[] $currencies currencies
     *
     * @return $this
     */
    public function setCurrencies($currencies)
    {
        $this->container['currencies'] = $currencies;

        return $this;
    }

    /**
     * Gets vouchers
     *
     * @return \Swagger\Client\Model\MarketplaceVoucher[]
     */
    public function getVouchers()
    {
        return $this->container['vouchers'];
    }

    /**
     * Sets vouchers
     *
     * @param \Swagger\Client\Model\MarketplaceVoucher[] $vouchers vouchers
     *
     * @return $this
     */
    public function setVouchers($vouchers)
    {
        $this->container['vouchers'] = $vouchers;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


