<?php
/**
 * OrderSerializerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketplace API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.10.8
 * Contact: support@lyra-network.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OrderSerializerTest Class Doc Comment
 *
 * @category    Class
 * @description OrderSerializer
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderSerializerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrderSerializer"
     */
    public function testOrderSerializer()
    {
    }

    /**
     * Test attribute "uuid"
     */
    public function testPropertyUuid()
    {
    }

    /**
     * Test attribute "href"
     */
    public function testPropertyHref()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "marketplace"
     */
    public function testPropertyMarketplace()
    {
    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }

    /**
     * Test attribute "alias"
     */
    public function testPropertyAlias()
    {
    }

    /**
     * Test attribute "awaiting_validation"
     */
    public function testPropertyAwaitingValidation()
    {
    }

    /**
     * Test attribute "buyer"
     */
    public function testPropertyBuyer()
    {
    }

    /**
     * Test attribute "shipping"
     */
    public function testPropertyShipping()
    {
    }

    /**
     * Test attribute "payment_config"
     */
    public function testPropertyPaymentConfig()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "initial_amount"
     */
    public function testPropertyInitialAmount()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "webhook_result"
     */
    public function testPropertyWebhookResult()
    {
    }

    /**
     * Test attribute "url_return"
     */
    public function testPropertyUrlReturn()
    {
    }

    /**
     * Test attribute "url_success"
     */
    public function testPropertyUrlSuccess()
    {
    }

    /**
     * Test attribute "url_refused"
     */
    public function testPropertyUrlRefused()
    {
    }

    /**
     * Test attribute "url_cancel"
     */
    public function testPropertyUrlCancel()
    {
    }

    /**
     * Test attribute "url_error"
     */
    public function testPropertyUrlError()
    {
    }

    /**
     * Test attribute "return_mode"
     */
    public function testPropertyReturnMode()
    {
    }

    /**
     * Test attribute "shop_url"
     */
    public function testPropertyShopUrl()
    {
    }

    /**
     * Test attribute "links"
     */
    public function testPropertyLinks()
    {
    }

    /**
     * Test attribute "vads_transaction_id"
     */
    public function testPropertyVadsTransactionId()
    {
    }

    /**
     * Test attribute "vads_transaction_date"
     */
    public function testPropertyVadsTransactionDate()
    {
    }

    /**
     * Test attribute "expected_capture_date"
     */
    public function testPropertyExpectedCaptureDate()
    {
    }

    /**
     * Test attribute "capture_delay"
     */
    public function testPropertyCaptureDelay()
    {
    }

    /**
     * Test attribute "persist_url"
     */
    public function testPropertyPersistUrl()
    {
    }

    /**
     * Test attribute "expiry_date"
     */
    public function testPropertyExpiryDate()
    {
    }
}
