<?php
/**
 * OrderLinksTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketplace API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.10.8
 * Contact: support@lyra-network.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OrderLinksTest Class Doc Comment
 *
 * @category    Class
 * @description OrderLinks
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderLinksTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrderLinks"
     */
    public function testOrderLinks()
    {
    }

    /**
     * Test attribute "items"
     */
    public function testPropertyItems()
    {
    }

    /**
     * Test attribute "transactions"
     */
    public function testPropertyTransactions()
    {
    }

    /**
     * Test attribute "refunds"
     */
    public function testPropertyRefunds()
    {
    }

    /**
     * Test attribute "execute"
     */
    public function testPropertyExecute()
    {
    }

    /**
     * Test attribute "execute_embedded"
     */
    public function testPropertyExecuteEmbedded()
    {
    }

    /**
     * Test attribute "execute_mit"
     */
    public function testPropertyExecuteMit()
    {
    }
}
