<?php
/**
 * ItemsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketplace API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.10.8
 * Contact: support@lyra-network.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ItemsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ItemsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for itemsActivate
     *
     * Activates the item, i.e. toggles `hold_payment` to false..
     *
     */
    public function testItemsActivate()
    {
    }

    /**
     * Test case for itemsCreate
     *
     * Creates an item..
     *
     */
    public function testItemsCreate()
    {
    }

    /**
     * Test case for itemsList
     *
     * List of items by order, by seller or by creation date..
     *
     */
    public function testItemsList()
    {
    }

    /**
     * Test case for itemsRead
     *
     * Retrieves the details of an item..
     *
     */
    public function testItemsRead()
    {
    }

    /**
     * Test case for itemsTransfersList
     *
     * List of transfers by order, by seller, by item, by transaction or by creation date..
     *
     */
    public function testItemsTransfersList()
    {
    }

    /**
     * Test case for itemsUpdate
     *
     * Updates an existing item.
     *
     */
    public function testItemsUpdate()
    {
    }
}
