<?php
/**
 * RegistrationsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketplace API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.10.8
 * Contact: support@lyra-network.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * RegistrationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RegistrationsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for registrationsCreate
     *
     * Creates a registration..
     *
     */
    public function testRegistrationsCreate()
    {
    }

    /**
     * Test case for registrationsDocumentsCreate
     *
     * Creates a registration document..
     *
     */
    public function testRegistrationsDocumentsCreate()
    {
    }

    /**
     * Test case for registrationsDocumentsList
     *
     * List of documents by registration..
     *
     */
    public function testRegistrationsDocumentsList()
    {
    }

    /**
     * Test case for registrationsList
     *
     * Retrieves the list of registrations by marketplace..
     *
     */
    public function testRegistrationsList()
    {
    }

    /**
     * Test case for registrationsRead
     *
     * Retrieves a single registration..
     *
     */
    public function testRegistrationsRead()
    {
    }

    /**
     * Test case for registrationsStatus
     *
     * Retrieves the status of a single registration. Deprecated: use registration_read instead..
     *
     */
    public function testRegistrationsStatus()
    {
    }

    /**
     * Test case for registrationsSubmit
     *
     * Submits the registration for examination by our services..
     *
     */
    public function testRegistrationsSubmit()
    {
    }

    /**
     * Test case for registrationsUpdate
     *
     * Updates a registration..
     *
     */
    public function testRegistrationsUpdate()
    {
    }
}
